// Fork-only («Читанка» / Chytanka): Ukrainian table for i18n.js. Keys are the
// English strings exactly as CrossInk's portal shows them (trimmed, runs of
// whitespace collapsed); a leading emoji/symbol prefix is kept by i18n.js, so
// "📤 Upload" only needs "Upload". Re-check after every CrossInk rebase that
// touches web/: a changed English string silently stays English.
// Terminology follows lib/I18n/translations/ukrainian.yaml: upload to the
// device = «надіслати», download to the computer = «завантажити».
window.CHYTANKA_I18N = (function () {
  function plural(n, one, few, many) {
    n = Math.abs(n) % 100;
    var n1 = n % 10;
    if (n > 10 && n < 20) return many;
    if (n1 === 1) return one;
    if (n1 >= 2 && n1 <= 4) return few;
    return many;
  }
  return {
    lang: "uk",
    dict: {
      // Shared chrome (base.html, Chytanka variant)
      "Читанка · based on CrossInk · Open Source": "Читанка · на основі CrossInk · відкритий код",
      "Home": "Головна",
      "File Manager": "Файли",
      "Settings": "Налаштування",
      "Fonts": "Шрифти",
      "Files · Читанка": "Файли · Читанка",
      "Settings · Читанка": "Налаштування · Читанка",
      "Fonts · Читанка": "Шрифти · Читанка",

      // Home
      "Device Status": "Стан пристрою",
      "Serial #": "Серійний №",
      "Version": "Версія",
      "WiFi Status": "Wi-Fi",
      "Connected": "Під’єднано",
      "IP Address": "IP-адреса",
      "Free Memory": "Вільна пам’ять",

      // File manager
      "Upload": "Надіслати",
      "New Folder": "Нова тека",
      "Delete Selected": "Видалити вибране",
      "Some files failed to upload": "Деякі файли не вдалося надіслати",
      "Dismiss": "Закрити",
      "Retry All Failed Uploads": "Повторити всі невдалі",
      "Retry": "Повторити",
      "Contents": "Вміст",
      "Name": "Назва",
      "Type": "Тип",
      "Size": "Розмір",
      "Actions": "Дії",
      "FOLDER": "ТЕКА",
      "This folder is empty": "Тека порожня",
      "An error occurred while loading the files": "Не вдалося завантажити список файлів",
      "Delete folder": "Видалити теку",
      "Delete file": "Видалити файл",
      "Move file": "Перемістити файл",
      "Rename file": "Перейменувати файл",
      "Upload file": "Надіслати файл",
      "Select a file to upload to": "Виберіть файл, щоб надіслати до",
      "Drop files here — or click to browse": "Перетягніть файли сюди — або натисніть, щоб вибрати",
      "Optimize EPUB": "Оптимізувати EPUB",
      "Advanced Mode": "Розширені параметри",
      "Rename from Book Metadata": "Назва з метаданих книжки",
      "Use Title - Author.epub when available": "Назва - Автор.epub, якщо є дані",
      "True-Grayscale": "Справжні відтінки сірого",
      "Fix SVG": "Виправити SVG",
      "Split Long Sections": "Ділити довгі розділи",
      "Break oversized chapters into smaller reader-friendly sections":
        "Розбивати завеликі розділи на менші, зручніші для читалки",
      "Keep Cover in Color": "Кольорова обкладинка",
      "Resize the cover safely without grayscale conversion": "Лише змінити розмір обкладинки, без перетворення на сірий",
      "JPEG Quality": "Якість JPEG",
      "Minimum quality": "Мінімальна якість",
      "Low quality": "Низька якість",
      "Medium-low quality": "Нижча за середню якість",
      "Medium quality": "Середня якість",
      "High quality": "Висока якість",
      "Maximum quality": "Максимальна якість",
      "Characters per Page": "Символів на сторінку",
      "Character count used for stable page-number metadata": "Кількість символів для сталих номерів сторінок",
      "Target Device": "Пристрій",
      "Auto": "Авто",
      "Rotation Direction": "Напрямок повороту",
      "CCW": "Проти год. стрілки",
      "CW": "За год. стрілкою",
      "Min Overlap": "Мін. перекриття",
      "Auto-download Log": "Автозавантаження журналу",
      "Export detailed log with statistics": "Зберегти докладний журнал зі статистикою",
      "Remember Settings": "Запам’ятати параметри",
      "Store these upload options in this browser": "Зберегти ці параметри в цьому браузері",
      "Image Processing Options": "Обробка зображень",
      "0 images": "0 зображень",
      "Cover": "Обкладинка",
      "Separator": "Роздільник",
      "Normal": "Звичайне",
      "H-Split": "Поділ по горизонталі",
      "V-Split": "Поділ по вертикалі",
      "Rotate": "Поворот",
      "Converting will modify files and can break hash‑based sync. ⚠️":
        "Перетворення змінює файли й може зламати синхронізацію за хешем. ⚠️",
      "Please back up or disable sync before proceeding.":
        "Перед продовженням зробіть резервну копію або вимкніть синхронізацію.",
      "Optimize & Upload": "Оптимізувати й надіслати",
      "Cancel": "Скасувати",
      "Conversion Log": "Журнал перетворення",
      "Create a new folder in": "Нова тека в",
      "Folder name... (use . for hidden)": "Назва теки... (. на початку — прихована)",
      "Create Folder": "Створити теку",
      "Delete Item(s)": "Видалити",
      "This action cannot be undone. Folders and everything inside them will be deleted.":
        "Цю дію не можна скасувати. Теки буде видалено разом з усім вмістом.",
      "Are you sure you want to delete the following item(s)?": "Видалити такі файли й теки?",
      "Delete": "Видалити",
      "Deleting...": "Видалення...",
      "Rename File": "Перейменувати файл",
      "Renaming": "Перейменування:",
      "New file name...": "Нова назва файлу...",
      "Rename": "Перейменувати",
      "Move File": "Перемістити файл",
      "Moving": "Переміщення:",
      "/Destination/Folder": "/Тека/Призначення",
      "Move": "Перемістити",
      "Preview": "Перегляд",
      "Download": "Завантажити",
      "Upload cancelled by User!": "Надсилання скасовано.",
      "All uploads complete!": "Усі файли надіслано!",
      "Uploading original file instead...": "Надсилаю оригінальний файл...",
      "Network connection restored": "З’єднання відновлено",
      "Network connection lost": "З’єднання втрачено",
      "Network error": "Помилка мережі",
      "Network error - upload interrupted": "Помилка мережі — надсилання перервано",
      "Upload failed": "Не вдалося надіслати",
      "Upload aborted": "Надсилання перервано",
      "Cancelled by user": "Скасовано",
      "WebSocket connection failed": "Не вдалося з’єднатися через WebSocket",
      "WebSocket closed during upload": "З’єднання WebSocket закрилося під час надсилання",
      "Please select at least one file!": "Виберіть хоча б один файл!",
      "Please select at least one item to delete.": "Виберіть хоча б один файл чи теку для видалення.",
      "Please enter a folder name!": "Введіть назву теки!",
      "Please enter a new name.": "Введіть нову назву.",
      "Please enter a destination folder.": "Вкажіть теку призначення.",
      'Folder name cannot contain " * : < > ? / \\ | and must not be . or ..':
        'Назва теки не може містити " * : < > ? / \\ | і не може бути . чи ..',
      'File name cannot contain " * : < > ? / \\ | and must not be . or ..':
        'Назва файлу не може містити " * : < > ? / \\ | і не може бути . чи ..',
      "Failed to create folder - network error": "Не вдалося створити теку — помилка мережі",
      "Failed to rename - network error": "Не вдалося перейменувати — помилка мережі",
      "Failed to move - network error": "Не вдалося перемістити — помилка мережі",
      "Failed to delete - network error": "Не вдалося видалити — помилка мережі",
      "This EPUB is DRM-protected. Please remove DRM before optimizing it.":
        "Ця книжка захищена DRM. Зніміть захист перед оптимізацією.",
      "This EPUB has invalid encryption metadata and cannot be optimized safely.":
        "Ця книжка має пошкоджені дані шифрування, її не можна безпечно оптимізувати.",
      "Conversion complete!": "Перетворення завершено!",
      "Conversion Summary": "Підсумок перетворення",
      "Batch Conversion Summary": "Підсумок пакетного перетворення",
      "Images found": "Знайдено зображень",
      "Images processed": "Оброблено зображень",
      "EPUB repairs": "Виправлення EPUB",
      "None needed": "Не потрібні",
      "Original size": "Початковий розмір",
      "Optimized size": "Після оптимізації",
      "Saved": "Заощаджено",
      "Time": "Час",
      "Files processed": "Оброблено файлів",
      "Successful": "Успішно",
      "Failed": "Не вдалося",
      "Total images processed": "Усього оброблено зображень",
      "Total fixes applied": "Усього виправлень",
      "Total splits": "Усього поділів",
      "Total original": "Разом до",
      "Total optimised": "Разом після",
      "Total saved": "Разом заощаджено",
      "Total time": "Загальний час",
      "Success": "Успішно",

      // Settings page
      "Save Settings": "Зберегти налаштування",
      "Saving...": "Збереження...",
      "No changes to save.": "Немає змін для збереження.",
      "Settings saved successfully!": "Налаштування збережено!",
      "Save failed": "Не вдалося зберегти",
      "Failed to load settings": "Не вдалося завантажити налаштування",
      "Failed to load": "Не вдалося завантажити",
      "Wi-Fi Networks": "Мережі Wi-Fi",
      "No Wi-Fi networks saved": "Немає збережених мереж Wi-Fi",
      "Add Network": "Додати мережу",
      "Last connected network": "Остання під’єднана мережа",
      "Password": "Пароль",
      "(unchanged)": "(без змін)",
      "Save": "Зберегти",
      "SSID is required.": "Потрібна назва мережі (SSID).",
      "Wi-Fi network saved!": "Мережу Wi-Fi збережено!",
      "Delete this Wi-Fi network?": "Видалити цю мережу Wi-Fi?",
      "Wi-Fi network deleted": "Мережу Wi-Fi видалено",
      "OPDS Servers": "Сервери OPDS",
      "No OPDS servers configured": "Немає серверів OPDS",
      "Add Server": "Додати сервер",
      "Server Name": "Назва сервера",
      "Username": "Ім’я користувача",
      "Filename": "Назва файлу",
      "Author - Title": "Автор - Назва",
      "Title - Author": "Назва - Автор",
      "OPDS server saved!": "Сервер OPDS збережено!",
      "Delete this OPDS server?": "Видалити цей сервер OPDS?",
      "OPDS server deleted": "Сервер OPDS видалено",

      // Fonts page
      "Installed Fonts": "Встановлені шрифти",
      "Upload Font": "Надіслати шрифт",
      "Loading...": "Завантаження...",
      "No fonts installed": "Шрифтів не встановлено",
      "Failed to load font list": "Не вдалося завантажити список шрифтів",
      "No .cpfont files found in the selected folder.": "У вибраній теці немає файлів .cpfont.",
      "No .cpfont files selected.": "Не вибрано файлів .cpfont.",
      "Please select files from a single font family.": "Виберіть файли одного шрифту.",
    },
    patterns: [
      [/^(.+) - Files - CrossInk Reader$/, "$1 · Файли · Читанка"],
      [
        /^(\d+) folders?, (\d+) files?, (.+)$/,
        function (_, d, f, size) {
          return d + " " + plural(+d, "тека", "теки", "тек") + ", " + f + " " + plural(+f, "файл", "файли", "файлів") + ", " + size;
        },
      ],
      [/^(\d+) images? \(all selectable\)$/, "Зображень: $1 (усі можна вибрати)"],
      [
        /^(\d+) images \((\d+) selectable, (.+)\)$/,
        function (_, n, sel, locked) {
          locked = locked.replace(/(\d+) cover/, "обкладинка: $1").replace(/(\d+) separators?/, "роздільники: $1");
          return "Зображень: " + n + " (можна вибрати " + sel + "; " + locked + ")";
        },
      ],
      [/^Max (\d+)×(\d+)px$/, "Макс. $1×$2 px"],
      [/^Auto \((.+)\)$/, "Авто ($1)"],
      [/^Batch mode: (\d+) EPUB\(s\) will use auto settings$/, "Пакетний режим: EPUB ($1) з автоматичними параметрами"],
      [/^(\d+)×(\d+) - Cover image \(locked\)$/, "$1×$2 — обкладинка (не змінюється)"],
      [/^(\d+)×(\d+) - Separator \(locked\)$/, "$1×$2 — роздільник (не змінюється)"],
      [/^Converting & uploading (.+)$/, "Перетворення й надсилання $1"],
      [/^Uploading (.+)$/, "Надсилання $1"],
      [/^Reading metadata for (.+)$/, "Читання метаданих: $1"],
      [/^Converting (.+)$/, "Перетворення $1"],
      [/^Conversion failed, uploading original (.+)$/, "Не вдалося перетворити, надсилаю оригінал $1"],
      [/^Conversion failed: (.+)$/, "Не вдалося перетворити: $1"],
      [/^Upload complete: (.+)$/, "Надіслано: $1"],
      [/^(\d+)\/(\d+) uploaded\. Failed: (.+)$/, "Надіслано $1 з $2. Не вдалося: $3"],
      [/^Upload failed for (.+?): (.+)$/, "Не вдалося надіслати $1: $2"],
      [/^Upload failed: (.+)$/, "Не вдалося надіслати: $1"],
      [/^Failed to check existing files: (.+)$/, "Не вдалося перевірити наявні файли: $1"],
      [/^Failed to create folder: (.*)$/, "Не вдалося створити теку: $1"],
      [/^Failed to rename: (.*)$/, "Не вдалося перейменувати: $1"],
      [/^Failed to move: (.*)$/, "Не вдалося перемістити: $1"],
      [/^Failed to delete (\d+) items?:$/, "Не вдалося видалити ($1):"],
      [/^Failed to delete some items: (.*)$/, "Не вдалося видалити деякі елементи: $1"],
      [/^Error: (.*)$/, "Помилка: $1"],
      [/^Delete font family "(.+)"\?$/, "Видалити шрифт «$1»?"],
      [/^Deleting (.+)\.\.\.$/, "Видалення $1..."],
      [/^Deleted "(.+)"\.$/, "Видалено «$1»."],
      [/^Failed to delete "(.+)"\.$/, "Не вдалося видалити «$1»."],
      [/^Delete error: (.+)$/, "Помилка видалення: $1"],
      [/^(\d+) files? → family "(.+)"$/, "Файлів: $1 → шрифт «$2»"],
      [/^Failed on (.+?): (.+)$/, "Помилка на файлі $1: $2"],
      [/^Upload error on (.+?): (.+)$/, "Помилка надсилання $1: $2"],
      [/^Uploaded (\d+) files? to family "(.+)"\.$/, "Надіслано файлів: $1, шрифт «$2»."],
      [/^([\d\s.,  ]+) bytes$/, "$1 байтів"],
    ],
  };
})();
