#pragma once

// Generated by scripts/chytanka/gen_embedded_quotes.py from the Chytanka brand
// repo (quotes/embedded_ids.json + cards/public/q###.bmp). Do not edit.
//
// Fork-only («Читанка»): quote cards for the default sleep screen. Each card is
// 480x800, 2 bits per pixel (0 black .. 3 white, leftmost pixel in the
// high bits), rows top-down, compressed as one raw deflate stream with a
// 512-byte window. See docs/chytanka/RELEASING.md.

#include <cstdint>

namespace chytanka {

struct QuoteCardEntry {
  uint32_t offset;   // into QUOTE_CARD_DATA
  uint32_t crc32;    // CRC-32 (zlib) of the decoded rows
  uint16_t size;     // compressed bytes
  uint16_t quoteId;  // id in brand/quotes/quotes.json
};

constexpr int QUOTE_CARD_WIDTH = 480;
constexpr int QUOTE_CARD_HEIGHT = 800;
constexpr int QUOTE_CARD_ROW_BYTES = 120;
constexpr unsigned QUOTE_CARD_WINDOW_SIZE = 512;
constexpr int QUOTE_CARD_COUNT = 50;
constexpr uint32_t QUOTE_CARD_DATA_SIZE = 311151;

extern const QuoteCardEntry QUOTE_CARDS[QUOTE_CARD_COUNT];
extern const uint8_t QUOTE_CARD_DATA[QUOTE_CARD_DATA_SIZE];

}  // namespace chytanka
