#!/usr/bin/env python3
"""Generate the embedded Chytanka quote cards (fork-only, «Читанка»).

Reads the curated card list (brand/quotes/embedded_ids.json) and the rendered
cards (brand/cards/public/q###.bmp: 480x800, 8-bit grayscale quantised to the
four native levels 0/85/170/255), and writes:

  src/images/ChytankaQuoteCards.h    table layout + constants
  src/images/ChytankaQuoteCards.cpp  compressed card data (flash)

Card encoding (decoded by src/activities/boot_sleep/ChytankaQuoteDecoder.cpp):
  * 2 bits per pixel, level = gray >> 6 (0 black .. 3 white), four pixels per
    byte, leftmost pixel in the two most significant bits -- the same packing
    GfxRenderer::drawBitmap() gets from Bitmap::readNextRow();
  * rows top-down, 120 bytes each, no padding;
  * one raw deflate stream per card (no zlib header), compressed with a
    512-byte window (wbits 9) so the device inflates row by row through a
    512-byte ring instead of a 32 KB window;
  * CRC-32 (zlib polynomial) of the decoded rows, checked on device.

Usage (from the firmware repo root):
  python3 scripts/chytanka/gen_embedded_quotes.py --brand <path/to/chytanka/brand>
  python3 scripts/chytanka/gen_embedded_quotes.py --brand ... --render   # re-render cards via make_cards.render()

--brand defaults to $CHYTANKA_BRAND_DIR. The tables sit between clang-format off/on
markers, so ./bin/clang-format-fix leaves the generated files untouched.
"""
import argparse
import json
import os
import sys
import zlib
from pathlib import Path

from PIL import Image

WIDTH, HEIGHT = 480, 800
ROW_BYTES = WIDTH // 4
WINDOW_BITS = 9
LEVELS = {0: 0, 85: 1, 170: 2, 255: 3}
BYTES_PER_LINE = 19  # "0xAB, " x 19 + indent stays within the 120-column limit

REPO = Path(__file__).resolve().parents[2]
OUT_H = REPO / "src" / "images" / "ChytankaQuoteCards.h"
OUT_CPP = REPO / "src" / "images" / "ChytankaQuoteCards.cpp"


def load_card(brand: Path, qid: int, quotes: dict | None) -> Image.Image:
    if quotes is not None:
        sys.path.insert(0, str(brand / "quotes"))
        import make_cards  # noqa: E402  (brand-side renderer, needs cairosvg)

        return make_cards.render(quotes[qid])
    return Image.open(brand / "cards" / "public" / f"q{qid:03d}.bmp")


def pack(img: Image.Image, qid: int) -> bytes:
    img = img.convert("L")
    if img.size != (WIDTH, HEIGHT):
        sys.exit(f"q{qid:03d}: expected {WIDTH}x{HEIGHT}, got {img.size[0]}x{img.size[1]}")
    px = img.tobytes()
    out = bytearray()
    for i in range(0, len(px), 4):
        b = 0
        for v in px[i : i + 4]:
            if v not in LEVELS:
                sys.exit(f"q{qid:03d}: gray value {v} is not one of the native levels 0/85/170/255")
            b = (b << 2) | LEVELS[v]
        out.append(b)
    assert len(out) == ROW_BYTES * HEIGHT
    return bytes(out)


def deflate(raw: bytes) -> bytes:
    c = zlib.compressobj(9, zlib.DEFLATED, -WINDOW_BITS, 9)
    data = c.compress(raw) + c.flush()
    # Round trip with the same window: zlib rejects any distance beyond it.
    d = zlib.decompressobj(-WINDOW_BITS)
    if d.decompress(data) + d.flush() != raw or d.unused_data:
        sys.exit("deflate round trip failed")
    return data


def hex_lines(data: bytes) -> list[str]:
    return [
        "    " + " ".join(f"0x{b:02X}," for b in data[i : i + BYTES_PER_LINE])
        for i in range(0, len(data), BYTES_PER_LINE)
    ]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--brand", default=os.environ.get("CHYTANKA_BRAND_DIR"), help="chytanka brand/ directory")
    ap.add_argument("--render", action="store_true", help="render cards with make_cards.render() instead of BMPs")
    args = ap.parse_args()
    if not args.brand:
        sys.exit("pass --brand <chytanka/brand> or set CHYTANKA_BRAND_DIR")
    brand = Path(args.brand).resolve()

    ids = json.loads((brand / "quotes" / "embedded_ids.json").read_text(encoding="utf-8"))
    if len(ids) != len(set(ids)) or not 0 < len(ids) <= 64:
        sys.exit("embedded_ids.json must list 1..64 unique ids (the device picker uses a 64-bit mask)")
    quotes = None
    if args.render:
        quotes = {q["id"]: q for q in json.loads((brand / "quotes" / "quotes.json").read_text(encoding="utf-8"))}

    blob = bytearray()
    entries = []
    for qid in ids:
        raw = pack(load_card(brand, qid, quotes), qid)
        data = deflate(raw)
        if len(data) > 0xFFFF:
            sys.exit(f"q{qid:03d}: compressed card too large ({len(data)} B)")
        entries.append((len(blob), zlib.crc32(raw), len(data), qid))
        blob += data

    h = f"""#pragma once

// Generated by scripts/chytanka/gen_embedded_quotes.py from the Chytanka brand
// repo (quotes/embedded_ids.json + cards/public/q###.bmp). Do not edit.
//
// Fork-only («Читанка»): quote cards for the default sleep screen. Each card is
// {WIDTH}x{HEIGHT}, 2 bits per pixel (0 black .. 3 white, leftmost pixel in the
// high bits), rows top-down, compressed as one raw deflate stream with a
// {1 << WINDOW_BITS}-byte window. See docs/chytanka/RELEASING.md.

#include <cstdint>

namespace chytanka {{

struct QuoteCardEntry {{
  uint32_t offset;   // into QUOTE_CARD_DATA
  uint32_t crc32;    // CRC-32 (zlib) of the decoded rows
  uint16_t size;     // compressed bytes
  uint16_t quoteId;  // id in brand/quotes/quotes.json
}};

constexpr int QUOTE_CARD_WIDTH = {WIDTH};
constexpr int QUOTE_CARD_HEIGHT = {HEIGHT};
constexpr int QUOTE_CARD_ROW_BYTES = {ROW_BYTES};
constexpr unsigned QUOTE_CARD_WINDOW_SIZE = {1 << WINDOW_BITS};
constexpr int QUOTE_CARD_COUNT = {len(entries)};
constexpr uint32_t QUOTE_CARD_DATA_SIZE = {len(blob)};

extern const QuoteCardEntry QUOTE_CARDS[QUOTE_CARD_COUNT];
extern const uint8_t QUOTE_CARD_DATA[QUOTE_CARD_DATA_SIZE];

}}  // namespace chytanka
"""
    cpp = [
        "// Generated by scripts/chytanka/gen_embedded_quotes.py. Do not edit.",
        "// Fork-only («Читанка»): only compiled in when the build defines CHYTANKA.",
        "#ifdef CHYTANKA",
        "",
        '#include "ChytankaQuoteCards.h"',
        "",
        "namespace chytanka {",
        "",
        "// clang-format off",
        "const QuoteCardEntry QUOTE_CARDS[QUOTE_CARD_COUNT] = {",
    ]
    cpp += [f"    {{{o}, 0x{c:08X}, {s}, {q}}}," for o, c, s, q in entries]
    cpp += ["};", "", "const uint8_t QUOTE_CARD_DATA[QUOTE_CARD_DATA_SIZE] = {"]
    cpp += hex_lines(bytes(blob))
    cpp += ["};", "// clang-format on", "", "}  // namespace chytanka", "", "#endif  // CHYTANKA", ""]

    OUT_H.write_text(h, encoding="utf-8")
    OUT_CPP.write_text("\n".join(cpp), encoding="utf-8")
    print(f"{len(entries)} cards, {len(blob)} B compressed (avg {len(blob) // len(entries)} B/card)")
    print(f"wrote {OUT_H.relative_to(REPO)} and {OUT_CPP.relative_to(REPO)}")


if __name__ == "__main__":
    main()
